### ISSUE TITLE
Gzip - Grpc-Accept-Encoding

### ISSUE THREAD

**Issue by vipero07** [bufbuild/connect-web#230]
**Is your feature request related to a problem? Please describe.**
Using `createGrpcWebTransport` I can't get zipped responses. It would be nice if those were implemented.

**Describe the solution you'd like**
zip responses

**Describe alternatives you've considered**
Regular responses without gzip. Currently my grpc service returns an 800kb message when it is unzipped. Zipped the message becomes 90kb (it has a lot of repeat information and is highly compressible).

**Additional context**
When using the following interceptor with a grpc server that supports gzip:
```ts
const interceptor: Interceptor = (next) => async (req) => {
  req.header.set('Grpc-Accept-Encoding', 'gzip');
  return await next(req);
};
```
I get the following message:
`[unknown] illegal tag: field no 3 wire type 7`

My server is a dotnet implementation with the following setting:
```cs
services.AddGrpc(o =>
{
    o.ResponseCompressionLevel = System.IO.Compression.CompressionLevel.SmallestSize;
    o.ResponseCompressionAlgorithm = "gzip";
});
```

**Comment by timostamm** [comment]
We have been thinking about compression quite a bit, thank you for opening this issue!

Message-level compression (via `Grpc-Accept-Encoding` and `Grpc-Encoding`) is indeed not implemented in connect-web. We do not offer it because the [specification doc for web browsers explicitly advises against it](https://github.com/grpc/grpc-web/blob/master/doc/browser-features.md#compression). Instead, full-body compression with the standard `Accept-Encoding` and `Content-Encoding` fields is recommended. 

You can see it in use on the BSR and in Buf studio. For an extreme example, visit https://studio.buf.build, click "Select method", and select the repository "googleapis/googleapis". A call to `GetImage` will show up in the network inspector of your browser: 

<img width="688" alt="Screen Shot 2022-08-11 at 11 37 58" src="https://user-images.githubusercontent.com/4289451/184106129-18cd71f0-0d76-4f45-9cb2-b000c6c5782c.png">

The image is huge, but thanks to full-body gzip compression, the payload transferred over the wire is reduced to 5% of its original size. The compression is transparently handled by the browser. 

Kestrel currently doesn't offer built-in support for full-body compression, so you will have to add a middleware to enable it. See https://github.com/grpc/grpc-dotnet/issues/1276 for an example on how to set it up. 

While there are some benefits to the control `Grpc-Encoding` allows, we believe that relying on standard HTTP semantics is actually a good call. Closing this, but happy to hear your thoughts.

**Comment by vipero07** [comment]
Full body compression is actually a much better solution since it keeps in line with web standards. Thanks.

**Comment by iamricard** [comment]
Hi!

Apologies for post on a 4 year old issue, but could this be revisited now that the web does provide a native [`DecompressionStream` API supporting `gzip`](https://developer.mozilla.org/en-US/docs/Web/API/DecompressionStream/DecompressionStream)? Full-body compression works nicely for unary RPCs, but we have multiple use-cases for long-running server-streaming RPCs and the grpc-web spec recommendation does predate the existence of a browser-native decompression stream API, which only came out in May 2023.

An example on how to implement this in user-land would also help. Looking at the `createGrpcWebTransport` method I couldn't quite figure out how to add support message encoding in user-land.
