### ISSUE TITLE
Deprecation of `TypeRegistry` breaks the current releases

### ISSUE THREAD

**Issue by FPurchess** [bufbuild/connect-web#239]
**Describe the bug**

Installing & building the current version (0.1.0) of `@bufbuild/connect-web` fails.
The `TypeRegistry` had been deprecated but the current npm version still references it.
The issue had been fixed by https://github.com/bufbuild/connect-web/pull/225 but it is unreleased.

**To Reproduce**

```bash
yarn add @bufbuild/connect-web
yarn build
```

```
'TypeRegistry' is not exported by node_modules/@bufbuild/protobuf/dist/esm/index.js, imported by node_modules/@bufbuild/connect-web/dist/esm/connect-error.js
file: [...]/node_modules/@bufbuild/connect-web/dist/esm/connect-error.js:15:35
13: // limitations under the License.
14: import { Code, codeFromString, codeToString } from "./code.js";
15: import { Any, proto3, protoBase64, TypeRegistry } from "@bufbuild/protobuf";
```

**Comment by smaye81** [comment]
Hey @FPurchess.  Yeah, unfortunately this is a drawback in how Yarn behaves.  Yarn does not fail on incorrect peer deps.  It just gives a warning.  So if your `package.json` uses `protobuf@0.1.0` and `connect-web@0.1.0`, Yarn will warn you that `connect-web` needs `protobuf@0.0.10`, but will happily install `0.1.0` anyway.

We are planning on cutting a release of `connect-web` today, which will include the #225 fix and should hopefully resolve this issue.

In the meantime, I would recommend sticking with `@bufbuild/protobuf@0.0.10` for now.  I will respond here when the release is ready so that you can fully upgrade.

**Comment by FPurchess** [comment]
Thanks for the quick response @smaye81! I can confirm that vendoring `protobuf@0.0.10` as a hard dependency resolves my issue.

**Comment by smaye81** [comment]
Appreciate your patience, @FPurchess.  We published the latest release of [@bufbuild/connect-web](https://www.npmjs.com/package/@bufbuild/connect-web) and [@bufbuild/protoc-gen-connect-web](https://www.npmjs.com/package/@bufbuild/protoc-gen-connect-web) today.  You should hopefully be able to upgrade all libraries with no further issues.
