### ISSUE TITLE
Is it possible to download/upload files using a proto contract?

### ISSUE THREAD

**Issue by FlymeDllVa** [bufbuild/connect-web#264]
Is it possible to make a contract for uploading and downloading files?

**Comment by timostamm** [comment]
Hey Dmitry, 

are you familiar with the File API? Once you have a `File` object from an input field, you can use [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader)'s `readAsArrayBuffer()` to obtain the raw content.

You can use a `bytes` field in protobuf:

```proto
message MyFileToUpload {
  string name = 1;
  bytes content = 2;
}
```

And simply set the "content" field to the array buffer you have just read (wrap it in a `new Uint8Array`).

Closing this, but let us know if you encounter any problems.

**Comment by FlymeDllVa** [comment]
I probably didn't ask the question correctly, so I'll try again. Is it possible to describe in such a way that it is possible to load a file as if it were a link, not bytes? I understand that I can use readAsDataURL, but then the file will be put in as bytes, but I would like the URL. As an example: https://avatars.githubusercontent.com/u/4289451?v=4

**Comment by timostamm** [comment]
You want to download arbitrary data as a file from your web application? This is a typical problem for many web applications. 
I encourage you to take a look at the File API - URL.createObjectURL specifically - but to mind the constraints. Take a look at open source solutions like filesaver.js for solutions for compatibility issues with older browsers. For large payloads, it is advisable to use a resource endpoint that is separate from your regular API so that you can control resource usage (on your servers and in the client) adequately.
