### ISSUE TITLE
Boilerplate to catch an explicit stream cancellation feels unnecessary

### ISSUE THREAD

**Issue by dnsco** [bufbuild/connect-web#266]
It's a good deal of ceremony to set up an abortable stream, you have to make an abort controller, and pass its signal,

then when you trigger the abort you need to handle an error at point of iteration, which feels like it should be unnecessary given that it's requested behavior.

In brief, I'd like to not have to write the catch block in:
```Javascript
(async () => {
    for await (const resp of stream) {
      this.processResponse(resp);
    }
  })().catch((e) => {
    // silently catch cancellations which shouldn't be errors
    if (!(e instanceof ConnectError && e.code === Code.Canceled)) {
      throw e;
    }
})
```

note that this error handling code is very far (in a different) from the abort invocation, which is in a different file that spawns the request, so it's a lot of context to hold in one's head and feels pretty disconnected.

Thanks again for the library, I can't wait to see how it develops!

**Comment by dnsco** [comment]
Note that even with this error handling code the underlying ```DOMException: The operation was aborted. ``` is thrown in another codepath and appears uncatchable.

**Comment by timostamm** [comment]
Dennis, could you give us some details about your environment regarding your second comment? The cancellation exception should be caught by connect-web, and be converted into a ConnectError with the appropriate code. It is possible that you are on a runtime that doesn't use the name property correctly. I'd like to look into that, but need information about your environment to be able to reproduce.

**Comment by timostamm** [comment]
Regarding your original comment, we can simplify the problem statement a bit:

```ts
async function main(longRunning: Promise<number>) {
  const result = await longRunning;
  console.log("done", result);
}
```

When this function runs, the interpreter steps through the code, and suspends until the promise `longRunning` is resolved, then it continues to the log statement. Under the hood, async/await is just syntactic sugar for promises, and lets you write asynchronous code like procedural code.

The problem is, promises do not have a concept of cancellation (they either resolve, which means `await` returns the promised value, or the reject, which means `await` throws an error). So when cancellation was added to the fetch API, it was done with AbortError. This follows the design of async/await in C# (whether it was intentional or by coincidence, I do not know). Unfortunately, ECMAScript lacks a few language features that make this design ergonomic to use, and (as far as I am aware) there is no widespread handling of AbortError as something to ignore in the JS frameworks out there.

We obviously cannot change the ECMAScript language with connect-web, and we are very hesitant to change the standard behavior of raising an error on cancellation. That is why `usePromiseClient()` raises an error instead of - for example - returning an object with distinct properties `cancelled`, `error` and `message`. It works out for most use cases, but you don't _have_ to use it. In fact, we encourage you to [write your own client](https://connect.build/docs/web/using-clients/#roll-your-own-client).

**Comment by dnsco** [comment]
I can remove the errors with:

``` JAVASCRIPT
        try {
          for await (const resp of stream) {
            this.processResponse(resp);
          }
        } catch (e) {
          if (
            !(
              (e instanceof ConnectError && e.code === Code.Canceled) ||
              (e instanceof DOMException && e.name === "AbortError")
            )
          ) {
            throw e;
          }
 ```

this issue is surfacing cancelling streaming responses with the grpc-web-transport (in firefox if that matters). If I remove the ConnectError or DomException line an error shows up in my console, I'm not sure if your above comment means both errors or desired behavior.

This is in a react app that streams responses to the client, when the user changes some parameters the existing stream is closed and a new one is initiated. For my use case, ideally I would like the AsyncIterable to just be done when abort() is called, rather than raising an error, though I can understand why you would want to raise for symmetry with the fetchApi.  

That said, it would be nice to only raise one error rather than two (as is currently happening). I don't have access to the underlying fetch promise because it is private to the returned asynciterable. I guess the underlying promise must be getting leaked somewhere if the DomException is not the desired behavior..

Let me know if you have any more questions about my environment or if there is anything I can do to help debug this if it is in fact a bug.

**Comment by timostamm** [comment]
I'm not quite sure why we end up with two errors in the catch clause, but the fact that you see an AbortError is a bug - our goal is that you only need to handle ConnectError. 

I can reproduce with the example in this repository, by cancelling the server-streaming call on [this line](https://github.com/bufbuild/connect-web/blob/main/packages/example/src/main.ts#L36).

**Comment by timostamm** [comment]
This is going to be fixed in https://github.com/bufbuild/connect-web/pull/267

**Comment by dnsco** [comment]
Thanks!
