### ISSUE TITLE
Allow `redirect:"follow"` for fetch requests

### ISSUE THREAD

**Issue by matt-lewandowski** [bufbuild/connect-web#313]
**Is your feature request related to a problem? Please describe.**
The fetch request that is being used for grpc-web-transport has the redirect hardcoded as "error". We have Cloudflare setup to redirect when the token is expired, using the refresh token. 

**Describe the solution you'd like**
Can you make redirect have an optional paramter on options for "error" | "follow" | "manual", or just `RequestRedirect`

**Comment by matt-lewandowski** [comment]
Something like
```ts
 /**
   * Controls what the fetch client will do when the server responds
   * with a redirect.
   */
  redirect?: RequestRedirect;
```
init: {
              method: "POST",
              credentials: options.credentials ?? "same-origin",
              redirect: options.redirect ?? "error",
              mode: "cors",
            },
```ts

```

**Comment by timostamm** [comment]
Hey Matt, you need to make sure that when Cloudflare redirects to refresh the token, it also redirects back to the original URL that was requested. Note that it all happens in a fetch request initiated by a script, which is quite different from a browser requesting a document.

This can be tricky to get right, which is why we error by default. You can change this behavior with a simple interceptor though:

```ts
function followRedirectInterceptor(): Interceptor {
  return (next) => (req) => {
    req.init.redirect = "follow";
    return next(req);
  }
}
```

Please let us know if that works for you. We will consider adding an option.

**Comment by matt-lewandowski** [comment]
Thanks @timostamm, that's right we do. This has been our flow for a while now, but we only just noticed issues since we started replacing some of our grpc-web clients with connect-web. 
Thanks for the suggestion, that has worked beautifully. I hadn't considered just changing it inside of the interceptor 🙌
