### ISSUE TITLE
[Question] Do you consider supporting long-lasting server side streaming?

### ISSUE THREAD

**Issue by nico151999** [bufbuild/connect-web#366]
I would like to keep a connection between the web client and the server for quite some time so that I can push data to the client that emerge during the time of the connection.

I would like to know if you have considered any mechanisms like websockets or server-sent events to push data to a client who is connected to a streaming endpoint over a long time. If you have considered it I would like to ask you to share if you plan to implement it in the future and if not why. Thank you really much!

**Comment by fubhy** [comment]
Streaming is already supported (with some limitations based on browser version / http version, etc.) as noted in the docs here: https://connect.build/docs/protocol#streaming-rpc

**Comment by nico151999** [comment]
Thanks for the response, Sebastian. Seems like there was a misunderstanding. I had read the articles before. I assumed the connect protocol (not gRPC web) would also have a web equivalent just like gRPC web for gRPC. And I thought this protocol would still be about to be shaped. I could neither find something refuting my assumption nor something proving it which is why I asked if you consider adding further specs based on websockets and server sent events to your protocol spec. Additionally, I assumed you would intentionally set timeouts on server streaming RPCs on the client side since my client-server connection was always interrupted after 10 seconds. This was an issue with my custom Ingress controller in my Kubernetes cluster though so it had nothing to do with the web implementation of connect even though it further pushed me in the wrong direction of assuming this would be intentional.

Anyway, your answer makes me assume that connect-web is rather meant to fulfil the needs it can by only using the fetch API which allows for server streaming just like gRPC web. I hope my understanding of your goals is correct now. If it's not I would like to ask you to reopen this issue and clarify your plans. Thanks again!

**Comment by fubhy** [comment]
I see.

There is `connect` (the protocol), which is simply a fetch-compatible, `POST` based HTTP protocol that brings grpc to the browser on top of `connect`-compatible servers (`connect-go` exists already, `connect-node` is on the way, and others will surely follow).

This repository contains several packages, `connect-web` being one of them, which is essentially a grpc TypeScript client that supports multiple transports (`connect`, `grpc-web` and bare `grpc` [pull-request for that is currently pending]). Depending on your use-case, you can plug in different transports in the client and then communicate with a server as long as it is compatible with that transport.

For clients, that means, you can use `connect-web` within the browser using the `grpc-web` or the `connect` transport. And you can use the same code within a Node.js (or Deno, Bun, etc.) client but with the option of using the (upcoming) `grpc` transport there.

Servers can choose to support one or multiple (or all) of the transport protocols: The same server can be used for both your web / browser & backend consumers. Without requiring a complicated (Envoy, etc.) proxy layer!

> I could neither find something refuting my assumption nor something proving it which is why I asked if you consider adding further specs based on websockets and server sent events to your protocol spec

`connect` (thankfully) doesn't use websockets but relies on modern HTTP features to cover its streaming needs.

**Comment by nico151999** [comment]
This was really helpful when it comes to understanding what this project currently covers and in which direction development goes. Thanks a lot!

**Comment by kubijo** [comment]
Sorry to chime into an old issue, but it seemed like the best place context-wise to ask the question…

My question then is: The current setup of server streaming RPCs through a long-running Fetch HTTP Post requests does work, but debugging it through browsers' built-in network inspectors is impossible because they only show it in a sort of limbo state without any information regarding the connection and sent data.

> connect (thankfully) doesn't use websockets but relies on modern HTTP features to cover its streaming needs :-)

Could you please expand on the `thankfully` part?
I am sure you have good reasons to be wary of the WS protocol, but it was made specifically for this feature & the communication is then readable in the browser inspector.

I can concur that this might be a minimal concern in the whole context of things that need to work in an ecosystem, but debugging is a big part of application development and I currently don't see any alternative approach that would enable it on current architecture.

**Comment by StarpTech** [comment]
After reading the whole thread and considering the @kubijo DX issue, is there any reason Connect does not use SSE events for server-side streaming? It would simplify debugging a lot.

**Comment by fubhy** [comment]
> Could you please expand on the thankfully part?

Sorry, I only saw your comment just now because you didn't tag me :-)

"Thankfully" because plain http "just works". WebSockets are quite a bit of extra hassle. And unnecesserily so if your use cases doesn't even need full duplex streaming (which few use-cases actually do).

**Comment by kubijo** [comment]
@fubhy Sebastian, we have just bumped into a hard limitation stemming from those choices and I would be interested in your (and your colleagues) take on it.

The problem is that we are developing an application that must work over a `localhost` connection in production setting, which AFAIK means that we cannot have HTTP/2 and hit the very low limit of browsers' persistent connections. 

![Image](https://github.com/connectrpc/connect-es/assets/11244314/7d6e158d-4cac-4dce-adff-a16f8e03018d)

HTTP/2 is sadly not an option because browsers do not connect over that without SSL and valid SSL for localhost is not an option either.

- Web socket connection would be a solution here… but you don't have that.
- multiplexing some long-running streams in user-land through `oneof` would be another option, but I'm sure you also see that it's ugly as hell.

Is there anything else you guys see as a possible solution?
I know that some services used dynamic DNS to hack around the impossibility of getting an SSL cert for localhost, but has it's own complexities and some network devices block that.

**Comment by kubijo** [comment]
From a very long discussion with colleagues, we decided to try two approaches:
- implement a transport layer over WebSocket (likely 1:1, that is one ws connection for one RPC call). This will introduce extra latency due to the ws handshake, but otherwise seems like the way to go without (hopefully) too much of a massive rewrite
- sidestep the client-side libraries through a custom wasm-based module that will communicate through WebSocket (however will be decided by the backend guy that came with that idea)

All that said, should any of you have any pointers, hints & hard-earned experience, I would appreciate enormously if you shared it to help with ws transport layer… because I'm sure there will be unforeseen troubles.

----

Fun fact: The 6 connections per domain limit is seemingly applied across all tabs, not just one… maybe it was obvious to others, but it was an ugly surprise to me :facepalm:

**Comment by tmm1** [comment]
> From a very long discussion with colleagues, we decided to try two approaches:

Are you able to share any learnings from these experimental approaches?
