### ISSUE TITLE
Add support for @improbable-eng/grpc-web

### ISSUE THREAD

**Issue by euskadi31** [bufbuild/connect-web#416]
**Is your feature request related to a problem? Please describe.**

I would like to use @improbable-eng/grpc-web as a gRPC client to be able to use bidirectional streams

**Describe the solution you'd like**

Something similar to this but for @improbable-eng/grpc-web

```ts
import * as grpc from "@grpc/grpc-js";

const client = createGrpcClient(ElizaService, { 
   address: "localhost",
   channelCredentials: grpc.ChannelCredentials.createInsecure()
});

client.say({ sentence: "Hello" }, (err: grpc.ServiceError | null, value?: SayResponse) => {
  //       
});
```

**Comment by timostamm** [comment]
@euskadi31, according to their README, @improbable-eng/grpc-web is a:

> Library for making gRPC-Web requests from a browser

@bufbuild/connect-web implements the [Connect protocol](https://connect.build/docs/protocol/), but it also implements the gRPC-web protocol. To make a request with gRPC-web:

```ts
import { createGrpcWebTransport } from "@bufbuild/connect-web";

const transport = createGrpcWebTransport({
  baseUrl: "http://localhost",
});
const client = createPromiseClient(ElizaService, transport);
const res = await client.say({sentence: "Hello"});
```

You can find the documentation [here](https://connect.build/docs/web/choosing-a-protocol#grpc-web).

If you are asking for callback-based clients, you can simply use `createCallbackClient()` instead of `createPromiseClient()`. You also have to option to create your own client. This is documented [here](https://connect.build/docs/web/using-clients).

Closing this, but please feel free to comment in case I missed something.
